CREATE TABLE IF NOT EXISTS Authors (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS Publishers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Subjects (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Books (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    PUBLISHED_YEAR INTEGER,
    LANG TEXT,
    NOTES TEXT,
	ISBN TEXT,
	NUMBER_OF_PAGES INTEGER,
	NUMBER_OF_COPIES INTEGER,

    AUTHOR_ID01 INTEGER NOT NULL,
    AUTHOR_ID02 INTEGER,
    AUTHOR_ID03 INTEGER,
    AUTHOR_ID04 INTEGER,
    AUTHOR_ID05 INTEGER,
    AUTHOR_ID06 INTEGER,
    AUTHOR_ID07 INTEGER,
    AUTHOR_ID08 INTEGER,
    AUTHOR_ID09 INTEGER,
    AUTHOR_ID10 INTEGER,

    PUBLISHER_ID INTEGER,
    SUBJECT_ID INTEGER,

    FOREIGN KEY(AUTHOR_ID01) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID02) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID03) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID04) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID05) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID06) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID07) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID08) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID09) REFERENCES Authors (ID),
    FOREIGN KEY(AUTHOR_ID10) REFERENCES Authors (ID),

    FOREIGN KEY (PUBLISHER_ID) REFERENCES Publishers(ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES Subjects(ID)
);