CREATE VIEW BOOKS_JOINED AS

SELECT Books.ID AS BookID, Books.TITLE, Books.PUBLISHED_YEAR, Books.LANG, Books.NOTES, Books.ISBN, Books.NUMBER_OF_PAGES, Books.NUMBER_OF_COPIES,

Books.AUTHOR_ID01, Authors01.NAME AS AUTHOR_NAME01, Authors01.DESCRIPTION AS AUTHOR_DESCRIPTION01,
Books.AUTHOR_ID02, Authors02.NAME AS AUTHOR_NAME02, Authors02.DESCRIPTION AS AUTHOR_DESCRIPTION02,
Books.AUTHOR_ID03, Authors03.NAME AS AUTHOR_NAME03, Authors03.DESCRIPTION AS AUTHOR_DESCRIPTION03,
Books.AUTHOR_ID04, Authors04.NAME AS AUTHOR_NAME04, Authors04.DESCRIPTION AS AUTHOR_DESCRIPTION04,
Books.AUTHOR_ID05, Authors05.NAME AS AUTHOR_NAME05, Authors05.DESCRIPTION AS AUTHOR_DESCRIPTION05,
Books.AUTHOR_ID06, Authors06.NAME AS AUTHOR_NAME06, Authors06.DESCRIPTION AS AUTHOR_DESCRIPTION06,
Books.AUTHOR_ID07, Authors07.NAME AS AUTHOR_NAME07, Authors07.DESCRIPTION AS AUTHOR_DESCRIPTION07,
Books.AUTHOR_ID08, Authors08.NAME AS AUTHOR_NAME08, Authors08.DESCRIPTION AS AUTHOR_DESCRIPTION08,
Books.AUTHOR_ID09, Authors09.NAME AS AUTHOR_NAME09, Authors09.DESCRIPTION AS AUTHOR_DESCRIPTION09,
Books.AUTHOR_ID10, Authors10.NAME AS AUTHOR_NAME10, Authors10.DESCRIPTION AS AUTHOR_DESCRIPTION10,

Books.PUBLISHER_ID, Publishers.NAME AS PUBLISHER_NAME, Books.SUBJECT_ID, Subjects.NAME AS SUBJECT_NAME

FROM Books

LEFT JOIN Authors Authors01 ON Authors01.ID = Books.AUTHOR_ID01
LEFT JOIN Authors Authors02 ON Authors02.ID = Books.AUTHOR_ID02
LEFT JOIN Authors Authors03 ON Authors03.ID = Books.AUTHOR_ID03
LEFT JOIN Authors Authors04 ON Authors04.ID = Books.AUTHOR_ID04
LEFT JOIN Authors Authors05 ON Authors05.ID = Books.AUTHOR_ID05
LEFT JOIN Authors Authors06 ON Authors06.ID = Books.AUTHOR_ID06
LEFT JOIN Authors Authors07 ON Authors07.ID = Books.AUTHOR_ID07
LEFT JOIN Authors Authors08 ON Authors08.ID = Books.AUTHOR_ID08
LEFT JOIN Authors Authors09 ON Authors09.ID = Books.AUTHOR_ID09
LEFT JOIN Authors Authors10 ON Authors10.ID = Books.AUTHOR_ID10

LEFT JOIN Publishers ON Publishers.ID = Books.PUBLISHER_ID
LEFT JOIN Subjects ON Subjects.ID  = Books.SUBJECT_ID;